<?php return array (
  'email_type' => '1',
  'email_safe' => '',
  'mail_address' => '',
  'smtp' => '',
  'smtp_user' => '',
  'smtp_pwd' => '',
  'smtp_port' => '',
  'order_by' => 'new',
  'order_type' => 'asc',
  'list_type' => 'win',
  'auto_finish' => '1',
  'index_slide' => 'a:2:{i:0;a:3:{s:4:"name";s:45:"花的秘密，花的味道，中国好闺蜜";s:3:"url";s:20:"http://www.jooyea.cn";s:3:"img";s:39:"upload/2015/01/04/20150104111352912.jpg";}i:1;a:3:{s:4:"name";s:24:"来自云南的花味道";s:3:"url";s:20:"http://www.jooyea.cn";s:3:"img";s:39:"upload/2015/01/04/20150104111655163.jpg";}}',
  'name' => '百花味',
  'url' => 'http://www.baihuawei.com',
  'master' => '',
  'qq' => '',
  'email' => '',
  'mobile' => '',
  'phone' => '',
  'address' => '',
  'site_footer_code' => '<div class=\\"footer\\">	<p class=\\"links\\">		<a href=\\"\\">关于我们</a>|<a href=\\"\\">常见问题</a>|<a href=\\"\\">安全交易</a>|<a href=\\"\\">购买流程</a>|<a href=\\"\\">如何付款</a>|<a href=\\"\\">联系我们</a>|<a href=\\"\\">合作提案</a>	</p>	<p class=\\"copyright\\">		Powered by <a href=\\"http://www.aircheng.com\\">baihuawei.com</a>	</p>Copyright © 2014-2015 <a class=\\"copyys\\" target=\\"_blank\\" href=\\"http://www.miibeian.gov.cn/\\"><span style=\\"font-family:Simsun;line-height:normal;\\">滇ICP备10004243号-6</span></a></div>',
  'tax' => '10',
  'stockup_time' => '1',
  'regiment_time_limit' => '60',
  'index_seo_title' => '中国最大的时尚鲜花类产品特卖网',
  'index_seo_keywords' => '时尚鲜花产品,鲜花产品特卖,鲜花产品团购',
  'index_seo_description' => '百花味网，中国最大的时尚鲜花类产品特卖网。',
  'goods_no_pre' => 'SD',
)?>